export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"65e9c9c80072400020eaf81f",
				"65e9c9c80072400020eaf822"
			]
		},
		"65e9c9c80072400020eaf81f": {
			"id": "65e9c9c80072400020eaf81f",
			"name": "404",
			"pageUrl": "404"
		},
		"65e9c9c80072400020eaf822": {
			"id": "65e9c9c80072400020eaf822",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {},
		"seo": {
			"favicon_32px": "https://uploads.quarkly.io/65e9c9c80072400020eaf81a/images/logo.png?v=2024-03-07T15:14:05.710Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/65e9c9c80072400020eaf81a/images/logo.png?v=2024-03-07T15:14:05.710Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/65e9c9c80072400020eaf81a/images/logo.png?v=2024-03-07T15:14:05.710Z",
			"robotsFileType": "autogenerated"
		}
	}
}